### ISSUE TITLE
Working node?

### ISSUE THREAD

**Issue by Emily7777** [bitshares-cnvote/newbitshares-core#13]
Hi Folks,
i'm having trouble getting the nodes to connect for the web wallet.
I've tried the Hangzhou, Beijing, and Chongquin cnvote.vip nodes found here: https://wallet.nbs.plus/
So far, none connect.
Do I need to add another node manually?  If so what are the working nodes?

Thanks

**Comment by bitshares-cnvote** [comment]
You can use “wss://hk.nbs.plus” or local node.
